### ISSUE TITLE
Guzzle Error

### ISSUE THREAD

**Issue by kamyasimon** [patricpoba/mtn-momo-api-php#2]
$ php ./vendor/patricpoba/mtn-momo-api-php/src/SandboxUserProvision.php -k '6758a7ea55df47e7bf86af7a5794cdf8' -c 'http://pugicode.com'

Fatal error: Uncaught GuzzleHttp\Exception\RequestException: cURL error 60: SSL
certificate problem: unable to get local issuer certificate (see https://curl.ha
xx.se/libcurl/c/libcurl-errors.html) in C:\wamp64\www\momotest\vendor\guzzlehttp
\guzzle\src\Handler\CurlFactory.php:201
Stack trace:
#0 C:\wamp64\www\momotest\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(1
55): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\E
asyHandle), Array)
#1 C:\wamp64\www\momotest\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(1
05): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlH
andler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFa
ctory))
#2 C:\wamp64\www\momotest\vendor\guzzlehttp\guzzle\src\Handler\CurlHandler.php(4
3): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler
), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)
)
#3 C:\wamp64\www\momotest\vendor\guzzlehttp\guzzle\src\Handler\Proxy.php(28 in C
:\wamp64\www\momotest\vendor\patricpoba\mtn-momo-api-php\src\Http\GuzzleClient.p
hp on line 52

**Comment by patricpoba** [comment]
The MTN development server has not been really stable. Please try again to confirm if problem still persists.

**Comment by kamyasimon** [comment]
> The MTN development server has not been really stable. Please try again to confirm if problem still persists.

My guess is you areusing the BMatovu Laravel package..., am i right?

**Comment by patricpoba** [comment]
@kamyasimon  No please, this package does not make use of bmatovu/laravel-mtn-momo.

**Comment by kamyasimon** [comment]
Sorry, that's wasn't my intent infact you are mixing up things.
I was only looking for a php package to share with MoMo subscribers but you
do not support or update your package.
Your intent for responding was to close the issue after a full year.
