### ISSUE TITLE
Not an Issue

### ISSUE THREAD

**Issue by 16isaac89** [patricpoba/mtn-momo-api-php#6]
Hi Patrick,
1. Just wanted to Know how i can generate the 
"collectionApiSecret"  
 "collectionPrimaryKey"  
 "collectionUserId"

2 Is the environment live or production, thanks in advance

**Comment by patricpoba** [comment]
hi @16isaac89  
Please use the following platforms to get the needed support. 

Skype Group:  https://join.skype.com/cgNGP80mWRIN (recommended)

Whatsapp Group: https://chat.whatsapp.com/H3nqtWl6eAo471IYITryto (not really active)
