### ISSUE TITLE
no responds

### ISSUE THREAD

**Issue by Neba-Emmanuel** [patricpoba/mtn-momo-api-php#7]
hello devs, i don't get any responds from the api when running the collection product

**Comment by patricpoba** [comment]
@Neba-Emmanuel  If the issue is about the API endpoint itself, kindly seek support here https://momodeveloper.mtn.com/contact-support

**Comment by Neba-Emmanuel** [comment]
Ok

**Comment by Neba-Emmanuel** [comment]
But I don't know for one reason or the other I keep having blank response
