### ISSUE TITLE
The package does not work on php version 8.0 

### ISSUE THREAD

**Issue by nakamoto-dev** [patricpoba/mtn-momo-api-php#8]
` In PackageDiscoveryTrait.php line 308:
                                                                               
  Package patricpoba/mtn-momo-api-php has requirements incompatible with your  
   PHP version, PHP extensions and Composer version:                           
    - patricpoba/mtn-momo-api-php v0.2.2 requires php ^7.0 which does not mat  
  ch your installed version 8.0.19.                                            
                                                                               

require [--dev] [--dry-run] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--fixed] [--no-suggest] [--no-progress] [--no-update] [--no-install] [--update-no-dev] [-w|--update-with-dependencies] [-W|--update-with-all-dependencies] [--with-dependencies] [--with-all-dependencies] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--] [<packages>...]

    `

**Comment by nakamoto-dev** [comment]
please check out that issue of versions

**Comment by mkcircles** [comment]
Yes, i have the same issue

**Comment by nakamoto-dev** [comment]
you are supposed to sign contracts with mtn

**Comment by nakamoto-dev** [comment]
email me  at chumbadennis695@gmail.com I give you an error free package
