### ISSUE TITLE
Newer Guzzlehttp issue with the package

### ISSUE THREAD

**Issue by temgo** [patricpoba/mtn-momo-api-php#9]
Having issues using composer with guzzlehttp version (Maybe the version needed to be upgraded?)

Problem 1
    - Root composer.json requires patricpoba/mtn-momo-api-php * -> satisfiable by patricpoba/mtn-momo-api-php[v0.1, v0.2, v0.2.1, v0.2.2].
    - patricpoba/mtn-momo-api-php[v0.1, ..., v0.2.2] require guzzlehttp/guzzle ^6.5 -> found guzzlehttp/guzzle[6.5.0, ..., 6.5.8] but it conflicts with your root composer.json require (^7.4).

**Comment by patricpoba** [comment]
fixed
